version: '3.8'

services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - $MYSQL_EXPOSED_PORT:$MYSQL_DOCKER_PORT
      - $API_EXPOSED_PORT:$API_DOCKER_PORT
      - $DASHBOARD_EXPOSED_PORT:$DASHBOARD_DOCKER_PORT
      - $PUBLIC_EXPOSED_PORT:$PUBLIC_DOCKER_PORT
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - mynet

  api:
    container_name: portfolio-builder-api
    restart: unless-stopped
    build: .
    depends_on:
      - database
    command: npm run serve:api
    network_mode: "service:database"
    environment:
      DB_HOST: database

  dashboard:
    container_name: portfolio-builder-dashboard
    restart: unless-stopped
    build: .
    depends_on:
      - api
    command: npm run serve:dashboard
    network_mode: "service:database"
    environment:
      CHOKIDAR_USEPOLLING: true # Hot Module Reload (HMR)

  public:
    container_name: portfolio-builder-public
    restart: unless-stopped
    build: .
    depends_on:
      - api
    command: npm run serve:public
    network_mode: "service:database"
    environment:
      CHOKIDAR_USEPOLLING: true # Hot Module Reload (HMR)
      
volumes:
  database-volume:

networks:
  mynet:
    driver: bridge