version: '3'

services:
  api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run serve:api
    ports:
      - 3000:3000

  dashboard:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    depends_on:
      - api
    command: npm run serve:dashboard
    ports:
      - 4201:4200
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot Module Reload (HMR)

  public:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    depends_on:
      - api
    command: npm run serve:public
    ports:
      - 4202:4200
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot Module Reload (HMR)

volumes:
  mono-node-modules: null
